DECLARE @vendas TABLE (VE_COD INT, VE_TIPO INT, VE_ESTOQUE INT, VE_SETOR INT, VE_DIA INT, VE_FILA VARCHAR(255), VE_VAGAS INT, VE_TIPO_ESPECIFICO VARCHAR(255));

INSERT INTO @vendas (VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO)
SELECT VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO FROM [foliatropical2014].[dbo].[vendas] WHERE VE_BLOCK=0 AND D_E_L_E_T_=0;

DECLARE @loja TABLE (LI_COD INT, LO_COD INT, LO_CLIENTE INT, LO_PARCEIRO INT, LO_VENDEDOR INT, LO_DATA_COMPRA DATETIME, LO_VALOR_TOTAL FLOAT, LO_VALOR_PARCIAL FLOAT, LO_VALOR_ITEM FLOAT, 
LO_VALOR_ITEM_TABELA FLOAT, LO_VALOR_INGRESSOS FLOAT, LO_VALOR_ADICIONAIS FLOAT, LO_VALOR_TRANSFER FLOAT, LO_VALOR_DELIVERY FLOAT, LO_VALOR_DESCONTO FLOAT, LO_VALOR_OVER_INTERNO FLOAT, 
LO_VALOR_OVER_EXTERNO FLOAT, LO_COMISSAO INT, LO_PAGO TINYINT, LO_DEADLINE DATE, LO_TID VARCHAR(255), LO_FORMA_PAGAMENTO INT, LO_ANTIFRAUDE_STATUS VARCHAR(255), LO_ANTIFRAUDE_SCORE FLOAT, LI_INGRESSO INT, QTDE INT, ITENS INT, LO_ORIGEM VARCHAR(255), 
LO_DELIVERY TINYINT, LO_CLI_PERIODO VARCHAR(255), LO_RETIRADA VARCHAR(255), LO_ENTREGUE TINYINT, LO_ENTREGUE_NOME VARCHAR(255), LO_ENCAMINHADO TINYINT, LO_ENCAMINHADO_LOCAL VARCHAR(255), 
LO_MOTOQUEIRO_NOME VARCHAR(255), LO_RECEBIDO TINYINT, LO_RECEBIDO_LOCAL VARCHAR(255), LO_ATENDENTE_NOME VARCHAR(255), LO_DATA_PAGAMENTO DATE, LO_CLI_ENDERECO VARCHAR(255), LO_CLI_NUMERO VARCHAR(255), 
LO_CLI_COMPLEMENTO VARCHAR(255), LO_CLI_BAIRRO VARCHAR(255), LO_CLI_CIDADE VARCHAR(255), LO_CLI_ESTADO VARCHAR(255), LO_CLI_CEP VARCHAR(255), LO_CLI_CUIDADOS VARCHAR(255), LO_CLI_CELULAR VARCHAR(255), 
LO_CLI_PONTO_REFERENCIA VARCHAR(255), LO_CLI_DATA_ENTREGA DATE);


INSERT INTO @loja (LI_COD, LO_COD, LO_CLIENTE, LO_PARCEIRO, LO_VENDEDOR, LO_DATA_COMPRA, LO_VALOR_TOTAL, LO_VALOR_PARCIAL, LO_VALOR_ITEM, LO_VALOR_ITEM_TABELA, LO_VALOR_INGRESSOS, LO_VALOR_ADICIONAIS, 
LO_VALOR_TRANSFER, LO_VALOR_DELIVERY, LO_VALOR_DESCONTO, LO_VALOR_OVER_INTERNO, LO_VALOR_OVER_EXTERNO, LO_COMISSAO, LO_PAGO, LO_DEADLINE, LO_TID, LO_FORMA_PAGAMENTO, LO_ANTIFRAUDE_STATUS, LO_ANTIFRAUDE_SCORE, LI_INGRESSO, QTDE, ITENS, LO_ORIGEM, LO_DELIVERY, LO_CLI_PERIODO, LO_RETIRADA, LO_ENTREGUE, LO_ENTREGUE_NOME, LO_ENCAMINHADO, LO_ENCAMINHADO_LOCAL, LO_MOTOQUEIRO_NOME, LO_RECEBIDO, LO_RECEBIDO_LOCAL, LO_ATENDENTE_NOME	, LO_DATA_PAGAMENTO, LO_CLI_ENDERECO, LO_CLI_NUMERO, LO_CLI_COMPLEMENTO, LO_CLI_BAIRRO, LO_CLI_CIDADE, LO_CLI_ESTADO, LO_CLI_CEP, LO_CLI_CUIDADOS, LO_CLI_CELULAR, LO_CLI_PONTO_REFERENCIA, LO_CLI_DATA_ENTREGA)
SELECT MAX(li.LI_COD), l.LO_COD, l.LO_CLIENTE, MAX(l.LO_PARCEIRO), MAX(l.LO_VENDEDOR), MAX(l.LO_DATA_COMPRA), MAX(l.LO_VALOR_TOTAL), MAX(l.LO_VALOR_PARCIAL), li.LI_VALOR, li.LI_VALOR_TABELA, 
MAX(l.LO_VALOR_INGRESSOS), li.LI_VALOR_ADICIONAIS, li.LI_VALOR_TRANSFER, MAX(l.LO_VALOR_DELIVERY), li.LI_DESCONTO, li.LI_OVER_INTERNO, li.LI_OVER_EXTERNO, MAX(l.LO_COMISSAO), MAX(l.LO_PAGO), 
MAX(l.LO_DEADLINE), MAX(l.LO_TID), MAX(l.LO_FORMA_PAGAMENTO), MAX(l.LO_ANTIFRAUDE_STATUS), MAX(l.LO_ANTIFRAUDE_SCORE), li.LI_INGRESSO, COUNT (li.LI_COD), MAX(l.LO_NUM_ITENS), MAX(l.LO_ORIGEM), MAX(l.LO_DELIVERY), MAX(l.LO_CLI_PERIODO), MAX(l.LO_RETIRADA), 
MAX(l.LO_ENTREGUE), MAX(l.LO_ENTREGUE_NOME), MAX(l.LO_ENCAMINHADO), MAX(l.LO_ENCAMINHADO_LOCAL), MAX(l.LO_MOTOQUEIRO_NOME), MAX(l.LO_RECEBIDO), MAX(l.LO_RECEBIDO_LOCAL), MAX(l.LO_ATENDENTE_NOME), MAX(l.LO_DATA_PAGAMENTO), MAX(l.LO_CLI_ENDERECO), MAX(l.LO_CLI_NUMERO), MAX(l.LO_CLI_COMPLEMENTO), MAX(l.LO_CLI_BAIRRO), MAX(l.LO_CLI_CIDADE), MAX(l.LO_CLI_ESTADO), MAX(l.LO_CLI_CEP), MAX(l.LO_CLI_CUIDADOS), MAX(l.LO_CLI_CELULAR), MAX(l.LO_CLI_PONTO_REFERENCIA), MAX(l.LO_CLI_DATA_ENTREGA)
FROM [foliatropical2014].[dbo].[loja] l, [foliatropical2014].[dbo].[loja_itens] li WHERE l.LO_EVENTO=%evento% AND l.LO_COD=li.LI_COMPRA AND l.D_E_L_E_T_=0 AND li.D_E_L_E_T_=0
GROUP BY li.LI_INGRESSO, l.LO_COD, l.LO_CLIENTE, li.LI_VALOR, li.LI_VALOR_TABELA, li.LI_VALOR_TRANSFER, li.LI_VALOR_ADICIONAIS, li.LI_DESCONTO, li.LI_OVER_INTERNO, li.LI_OVER_EXTERNO;


DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), EMAIL VARCHAR(255), CGC_CPF VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC, EMAIL, CGC_CPF)
SELECT CODPARC, NOMEPARC, EMAIL, CGC_CPF FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';


DECLARE @parceiros TABLE (CODPARC INT, NOMEPARC VARCHAR(255));

INSERT INTO @parceiros (CODPARC, NOMEPARC)
SELECT CODPARC, NOMEPARC FROM [parceiros].[dbo].[TGFPAR] WHERE VENDEDOR='S';


SELECT
VOUCHER,
VENDEDOR_INTERNO AS 'VENDEDOR INTERNO',
CLIENTE,
PARCEIRO,
QTDE,
VALOR_ITEM AS 'VALOR ITEM',
TIPO,
ESPECIFICO,
DATA,
SETOR,
FILA,
VAGAS,
PAGO,
DEADLINE,
FORMA_PAGAMENTO AS 'FORMA PAGAMENTO',
ANTIFRAUDE_STATUS AS 'STATUS CLEARSALE',
ANTIFRAUDE_SCORE AS 'RISCO CLEARSALE',
DATA_COMPRA AS 'DATA COMPRA',
DATA_PAGAMENTO AS 'DATA DO PAGAMENTO',

ORIGEM AS 'ORIGEM DA VENDA',
RETIRADA AS 'RETIRADA',
RETIRADA_HORARIO AS 'RETIRADA HORÁRIO',
ENTREGUE,
ENTREGUE_NOME AS 'ENTREGUE PARA',
ENCAMINHADO,
ENCAMINHADO_LOCAL AS 'ENCAMINHADO PARA',
MOTOQUEIRO_NOME AS 'MOTOQUEIRO',
RECEBIDO,
RECEBIDO_LOCAL AS 'RECEBIDO EM',
ATENDENTE_NOME AS 'ATENDENTE',

DELIVERY,
ENTREGA_HORARIO AS 'ENTREGA HORÁRIO',
CLIENTE_ENDERECO AS ENDERECO,
CLIENTE_NUMERO AS 'NÚMERO',
CLIENTE_COMPLEMENTO AS COMPLEMENTO,
CLIENTE_BAIRRO AS BAIRRO,
CLIENTE_CIDADE AS CIDADE,
CLIENTE_ESTADO AS ESTADO,
CLIENTE_CEP AS CEP,
CLIENTE_CUIDADOS AS 'AOS CUIDADOS DE',
CLIENTE_CELULAR AS CELULAR,
CLIENTE_PONTO_REFERENCIA AS 'PONTO DE REFERÊNCIA',
CLIENTE_DATA_ENTREGA AS 'DATA DE ENTREGA'

FROM (

	SELECT
	*,
	(TRANSFER_UNITARIO * QTDE) AS TRANSFER,
	(DELIVERY_TOTAL / ITENS) AS VALOR_DELIVERY,
	(PRECO_AUTORIZADO * QTDE) AS VALOR_TOTAL_CALCULO_COMISSAO,
	(PRECO_PRATICADO * QTDE) AS PRECO_TOTAL_PRATICADO,
	(PRECO_PRATICADO + ADICIONAIS) AS VALOR_TOTAL_VENDA,
	(OVER_EXTERNO * QTDE) AS OVER_EXTERNO_TOTAL,
	((VALOR_ITEM - OVER_EXTERNO + OVER_INTERNO) * COMISSAO / 100) AS VALOR_COMISSAO
	FROM (
		SELECT 
		l.LO_COD AS VOUCHER,
		u.US_NOME AS VENDEDOR_INTERNO,
		c.NOMEPARC AS CLIENTE,
		p.NOMEPARC AS PARCEIRO,
		l.LO_VALOR_ITEM_TABELA AS VALOR_TABELA,
		l.LO_VALOR_DESCONTO AS VALOR_DESCONTO,
		l.LO_VALOR_OVER_INTERNO AS OVER_INTERNO,
		(l.LO_VALOR_ITEM_TABELA - l.LO_VALOR_DESCONTO + l.LO_VALOR_OVER_INTERNO) AS PRECO_AUTORIZADO,
		l.LO_VALOR_OVER_EXTERNO AS OVER_EXTERNO,
		(l.LO_VALOR_ITEM_TABELA + l.LO_VALOR_OVER_EXTERNO) AS PRECO_PRATICADO,
		l.QTDE AS QTDE,
		l.ITENS AS ITENS,
		l.LO_VALOR_ADICIONAIS AS ADICIONAIS,
		l.LO_VALOR_TRANSFER AS TRANSFER_UNITARIO,
		l.LO_VALOR_DELIVERY AS DELIVERY_TOTAL,
		l.LO_COMISSAO AS COMISSAO,
		l.LO_VALOR_ITEM AS VALOR_ITEM,
		
		CASE WHEN t.TI_NOME='Lounge' THEN 'Folia Tropical' ELSE t.TI_NOME END AS TIPO,
		ISNULL(v.VE_TIPO_ESPECIFICO,'') AS ESPECIFICO,
		CONVERT(VARCHAR, d.ED_DATA, 103) AS DATA,
		s.ES_NOME AS SETOR,
		ISNULL(v.VE_FILA,'') AS FILA,
		ISNULL(v.VE_VAGAS,'') AS VAGAS,
		CASE WHEN l.LO_PAGO=1 THEN 'PAGO' ELSE '' END AS PAGO,
		l.LO_DEADLINE AS DEADLINE,
		f.FP_NOME AS FORMA_PAGAMENTO,
		
		CASE
			WHEN l.LO_ANTIFRAUDE_STATUS='APA' THEN 'Aprovação Automática'
			WHEN l.LO_ANTIFRAUDE_STATUS='APM' THEN 'Aprovação Manual'
			WHEN l.LO_ANTIFRAUDE_STATUS='RPM' THEN 'Reprovado Sem Suspeita'
			WHEN l.LO_ANTIFRAUDE_STATUS='AMA' THEN 'Em Análise'
			WHEN l.LO_ANTIFRAUDE_STATUS='ERR' THEN 'Erro' 
			WHEN l.LO_ANTIFRAUDE_STATUS='NVO' THEN 'Não Classificado' 
			WHEN l.LO_ANTIFRAUDE_STATUS='SUS' THEN 'Suspensão Manual' 
			WHEN l.LO_ANTIFRAUDE_STATUS='CAN' THEN 'Cancelado' 
			WHEN l.LO_ANTIFRAUDE_STATUS='FRD' THEN 'Fraude Confirmada' 
			WHEN l.LO_ANTIFRAUDE_STATUS='RPA' THEN 'Reprovação Automática' 
			WHEN l.LO_ANTIFRAUDE_STATUS='RPP' THEN 'Reprovação por Política' 
		END AS ANTIFRAUDE_STATUS,
		
		CASE
			WHEN l.LO_ANTIFRAUDE_SCORE<30 THEN 'Risco Baixo'
			WHEN l.LO_ANTIFRAUDE_SCORE<60 THEN 'Risco Médio'
			WHEN l.LO_ANTIFRAUDE_SCORE<90 THEN 'Risco Alto'
			WHEN l.LO_ANTIFRAUDE_SCORE<100 THEN 'Risco Crítico'
		END AS ANTIFRAUDE_SCORE,

		CASE
			WHEN l.LO_ORIGEM='telefone' THEN 'Telefone'
			WHEN l.LO_ORIGEM='balcao' THEN 'Balcão'
			WHEN l.LO_ORIGEM='site' THEN 'Site'
			WHEN l.LO_ORIGEM='chatonline' THEN 'Chat Online'
			WHEN l.LO_ORIGEM='email' THEN 'E-mail' 
		END AS ORIGEM,

		CASE WHEN l.LO_DELIVERY=1 THEN 'SIM' ELSE '' END AS DELIVERY,
		CASE WHEN l.LO_ENTREGUE=1 THEN 'SIM' ELSE '' END AS ENTREGUE,
		CASE WHEN l.LO_ENCAMINHADO=1 THEN 'SIM' ELSE '' END AS ENCAMINHADO,
		CASE WHEN l.LO_RECEBIDO=1 THEN 'SIM' ELSE '' END AS RECEBIDO,


		l.LO_RETIRADA AS RETIRADA,
		CASE WHEN l.LO_RETIRADA IS NOT NULL AND l.LO_DELIVERY=0 THEN l.LO_CLI_PERIODO ELSE '-' END AS RETIRADA_HORARIO,
		l.LO_ENTREGUE_NOME AS ENTREGUE_NOME,
		l.LO_ENCAMINHADO_LOCAL AS ENCAMINHADO_LOCAL,
		l.LO_MOTOQUEIRO_NOME AS MOTOQUEIRO_NOME,
		l.LO_RECEBIDO_LOCAL AS RECEBIDO_LOCAL,
		l.LO_ATENDENTE_NOME AS ATENDENTE_NOME,

		CASE WHEN l.LO_DELIVERY=1 THEN l.LO_CLI_PERIODO ELSE '-' END AS ENTREGA_HORARIO,
		l.LO_CLI_ENDERECO AS CLIENTE_ENDERECO,
		l.LO_CLI_NUMERO AS CLIENTE_NUMERO,
		l.LO_CLI_COMPLEMENTO AS CLIENTE_COMPLEMENTO,
		l.LO_CLI_BAIRRO AS CLIENTE_BAIRRO,
		l.LO_CLI_CIDADE AS CLIENTE_CIDADE,
		l.LO_CLI_ESTADO AS CLIENTE_ESTADO,
		l.LO_CLI_CEP AS CLIENTE_CEP,
		l.LO_CLI_CUIDADOS AS CLIENTE_CUIDADOS,
		l.LO_CLI_CELULAR AS CLIENTE_CELULAR,
		l.LO_CLI_PONTO_REFERENCIA AS CLIENTE_PONTO_REFERENCIA,
		l.LO_CLI_DATA_ENTREGA AS CLIENTE_DATA_ENTREGA,

		l.LO_TID AS TID,
		l.LO_DATA_COMPRA AS DATA_COMPRA,
		l.LO_DATA_PAGAMENTO AS DATA_PAGAMENTO,
		d.ED_DATA

		FROM @loja l
		LEFT JOIN @vendas v ON v.VE_COD = l.LI_INGRESSO
		LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE
		LEFT JOIN @parceiros p ON p.CODPARC = l.LO_PARCEIRO
		LEFT JOIN [foliatropical2014].[dbo].[tipos] t ON t.TI_COD=v.VE_TIPO
		LEFT JOIN [foliatropical2014].[dbo].[eventos_dias] d ON d.ED_COD=v.VE_DIA
		LEFT JOIN [foliatropical2014].[dbo].[eventos_setores] s ON s.ES_COD=v.VE_SETOR
		LEFT JOIN [foliatropical2014].[dbo].[formas_pagamento] f ON f.FP_COD=l.LO_FORMA_PAGAMENTO
		LEFT JOIN [foliatropical2014].[dbo].[usuarios] u ON l.LO_VENDEDOR=u.US_COD
		WHERE d.D_E_L_E_T_=0 AND t.D_E_L_E_T_=0 AND s.D_E_L_E_T_=0
	) S 
) S ORDER BY TIPO ASC, ED_DATA ASC
