--Relatorio de clientes
DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), TELEFONE VARCHAR(255), EMAIL VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC, TELEFONE, EMAIL)
SELECT CODPARC, NOMEPARC, TELEFONE, EMAIL FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';

SELECT

NOME,
TELEFONE_CLIENTE AS 'TELEFONE',
EMAIL_CLIENTE AS 'EMAIL'

FROM (
	SELECT

	MAX(ISNULL(c.NOMEPARC, '')) AS NOME,
	MAX(ISNULL(CAST(c.TELEFONE AS CHAR), '')) AS TELEFONE_CLIENTE,
	MAX(ISNULL(c.EMAIL, '')) AS EMAIL_CLIENTE
	
	FROM [foliatropical2014].[dbo].[loja] l
	LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE


	WHERE l.LO_EVENTO=%evento% 
	AND l.LO_BLOCK=0 AND l.D_E_L_E_T_=0

	GROUP BY l.LO_CLIENTE
	
) S ORDER BY NOME ASC;