--Relatorio de Agendamentos Confirmados

DECLARE @vendas TABLE (VE_COD INT, VE_TIPO INT, VE_ESTOQUE INT, VE_SETOR INT, VE_DIA INT, VE_FILA VARCHAR(255), VE_VAGAS INT, VE_TIPO_ESPECIFICO VARCHAR(255));

INSERT INTO @vendas (VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO)
SELECT VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO FROM [foliatropical2014].[dbo].[vendas] WHERE VE_BLOCK=0 AND D_E_L_E_T_=0;

DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC)
SELECT CODPARC, NOMEPARC FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';

DECLARE @adicionais TABLE (COMPRA INT, ITEM INT, INCLUSO TINYINT, VALOR FLOAT);

INSERT INTO @adicionais (COMPRA, ITEM, INCLUSO, VALOR)
SELECT 
LIA_COMPRA AS COMPRA,
LIA_ITEM AS ITEM,
LIA_INCLUSO AS INCLUSO,
CASE WHEN LIA_INCLUSO=1 THEN 0.00 ELSE LIA_VALOR END AS VALOR 
FROM [foliatropical2014].[dbo].[loja_itens_adicionais]
WHERE LIA_ADICIONAL IN (SELECT VA_COD FROM [foliatropical2014].[dbo].[vendas_adicionais] WHERE VA_NOME_INSERCAO='transfer' OR VA_NOME_INSERCAO='transferinout')
AND LIA_BLOCK=0 AND D_E_L_E_T_=0;

SELECT

MAX(r.RO_NOME) AS ROTEIRO,
MAX(t.TR_NOME) AS TRANSPORTE,
MAX(CONVERT(VARCHAR, d.ED_DATA, 103)) AS DATA,
MAX(SUBSTRING(CONVERT(CHAR, th.TH_HORA, 8), 1, 5)) AS HORARIO,
MAX(l.LO_COD) AS VOUCHER,
--MAX(li.LI_ID) AS ITEM,
MAX(CASE WHEN a.INCLUSO=1 THEN 'INCLUSO' ELSE '-' END) AS INCLUSO,
MAX(CASE WHEN a.INCLUSO=1 THEN 0.00 ELSE a.VALOR END) AS VALOR,
MAX(li.LI_NOME) AS NOME,
MAX(c.NOMEPARC) AS CLIENTE,
MAX(CASE WHEN tp.TI_NOME='Lounge' THEN 'Folia Tropical' ELSE tp.TI_NOME END) AS TIPO,
--MAX(d.ED_NOME) AS DIA,
MAX(s.ES_NOME) AS SETOR,
MAX(CASE WHEN l.LO_PAGO=1 THEN 'PAGO' ELSE '' END) AS PAGO


FROM [foliatropical2014].[dbo].[transportes_agendamento] ta
LEFT JOIN [foliatropical2014].[dbo].[loja_itens] li ON li.LI_COD=ta.TA_ITEM
LEFT JOIN [foliatropical2014].[dbo].[loja] l ON l.LO_COD=li.LI_COMPRA
LEFT JOIN [foliatropical2014].[dbo].[transportes_horarios] th ON th.TH_COD=ta.TA_HORARIO
LEFT JOIN [foliatropical2014].[dbo].[transportes] t ON t.TR_COD=th.TH_TRANSPORTE
LEFT JOIN [foliatropical2014].[dbo].[roteiros] r ON r.RO_COD=t.TR_ROTEIRO

LEFT JOIN @vendas v ON v.VE_COD = li.LI_INGRESSO
LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE
LEFT JOIN @adicionais a ON a.COMPRA = l.LO_COD
LEFT JOIN [foliatropical2014].[dbo].[tipos] tp ON tp.TI_COD=v.VE_TIPO
LEFT JOIN [foliatropical2014].[dbo].[eventos_dias] d ON d.ED_COD=v.VE_DIA
LEFT JOIN [foliatropical2014].[dbo].[eventos_setores] s ON s.ES_COD=v.VE_SETOR

WHERE l.LO_EVENTO=%evento% 
AND l.LO_BLOCK=0 AND l.D_E_L_E_T_=0 AND li.D_E_L_E_T_=0
AND ta.TA_BLOCK=0 AND ta.D_E_L_E_T_=0
AND t.TR_BLOCK=0 AND t.D_E_L_E_T_=0 
AND th.TH_BLOCK=0 AND th.D_E_L_E_T_=0
AND r.RO_BLOCK=0 AND r.D_E_L_E_T_=0
AND d.D_E_L_E_T_=0 AND tp.D_E_L_E_T_=0 AND s.D_E_L_E_T_=0

GROUP BY li.LI_COD
ORDER BY ROTEIRO ASC, TRANSPORTE ASC, HORARIO ASC, VOUCHER ASC;