SELECT

  `CO_COD` AS 'COD',
  `CO_NOME` AS 'NOME',
  `CO_EMAIL` AS 'EMAIL',
  `CO_TELEFONE` AS 'TELEFONE',
  REPLACE(REPLACE(`CO_MENSAGEM`, '\r', ' '), '\n', ' ') AS 'MENSAGEM',
  `CO_DATA` AS 'DATA',
  `CO_ASSUNTO` AS 'ASSUNTO',
  `CO_VIA` AS 'VIA',
  `CO_SETOR` AS 'SETOR',
  `CO_ATENDENTE` AS 'ATENDENTE',
  `CO_RESPONSAVEL` AS 'RESPONSAVEL',
  `CO_STATUS` AS 'STATUS',
  REPLACE(REPLACE(`CO_SOLUCAO`, '\r', ' '), '\n', ' ') AS 'SOLUCAO',
  `CO_DATA_STATUS` AS 'DATA_STATUS',
  `CO_DATA_CONCLUSAO` AS 'DATA CONCLUSAO' 

FROM `contato`

WHERE `D_E_L_E_T_`<>'*'