--Relatorio de Logs

DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), EMAIL VARCHAR(255), CGC_CPF VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC, EMAIL, CGC_CPF)
SELECT CODPARC, NOMEPARC, EMAIL, CGC_CPF FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';


SELECT * FROM (
	SELECT
	log.LOG_USUARIO AS 'CLIENTE CÓDIGO',
	c.NOMEPARC AS 'CLIENTE NOME',
	c.EMAIL AS 'CLIENTE E-MAIL',
	log.LOG_PAGINA AS 'PÁGINA ACESSADA',
	ISNULL(CAST(REPLACE(REPLACE(CAST(log.LOG_CARRINHO AS NVarchar(MAX)), CHAR(10),' '), CHAR(13),' ') AS NText), '-') AS 'CARRINHO',
	log.LOG_DATA AS 'DATA',
	log.LOG_IP AS 'IP',
	log.LOG_HOST AS 'HOST',
	log.LOG_OBSERVACAO AS 'OBSERVAÇÃO'

	FROM [foliatropical2014].[dbo].[usuarios_log] log
	LEFT JOIN @clientes c ON c.CODPARC = log.LOG_USUARIO

	WHERE log.LOG_USUARIO=%cliente%
) S
