--Relatorio de Agendamentos Confirmados

DECLARE @vendas TABLE (VE_COD INT, VE_TIPO INT, VE_ESTOQUE INT, VE_SETOR INT, VE_DIA INT, VE_FILA VARCHAR(255), VE_VAGAS INT, VE_TIPO_ESPECIFICO VARCHAR(255));

INSERT INTO @vendas (VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO)
SELECT VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO FROM [foliatropical2014].[dbo].[vendas] WHERE VE_BLOCK=0 AND D_E_L_E_T_=0;

DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), TELEFONE VARCHAR(255), EMAIL VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC, TELEFONE, EMAIL)
SELECT CODPARC, NOMEPARC, TELEFONE, EMAIL FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';


DECLARE @adicionais TABLE (COMPRA INT, ITEM INT, INCLUSO TINYINT, VALOR FLOAT);

INSERT INTO @adicionais (COMPRA, ITEM, INCLUSO, VALOR)
SELECT 
LIA_COMPRA AS COMPRA,
LIA_ITEM AS ITEM,
LIA_INCLUSO AS INCLUSO,
CASE WHEN LIA_INCLUSO=1 THEN 0.00 ELSE LIA_VALOR END AS VALOR 
FROM [foliatropical2014].[dbo].[loja_itens_adicionais]
WHERE LIA_ADICIONAL IN (SELECT VA_COD FROM [foliatropical2014].[dbo].[vendas_adicionais] WHERE VA_NOME_INSERCAO='transfer' OR VA_NOME_INSERCAO='transferinout')
AND LIA_BLOCK=0 AND D_E_L_E_T_=0;


DECLARE @loja TABLE (LO_COD INT, LO_CLIENTE INT, LO_FORMA_PAGAMENTO INT, LO_VALOR_TOTAL DECIMAL(10,2), LO_DATA_COMPRA DATETIME, LO_PAGO TINYINT, LO_DELIVERY TINYINT, LO_RETIRADA VARCHAR(255), LO_CLI_PERIODO VARCHAR(255), LO_CLI_DATA_ENTREGA DATETIME);

INSERT INTO @loja (LO_COD, LO_CLIENTE, LO_FORMA_PAGAMENTO, LO_VALOR_TOTAL, LO_DATA_COMPRA, LO_PAGO, LO_DELIVERY, LO_RETIRADA, LO_CLI_PERIODO, LO_CLI_DATA_ENTREGA)
SELECT LO_COD, 
LO_CLIENTE, 
LO_FORMA_PAGAMENTO, 
LO_VALOR_TOTAL, 
LO_DATA_COMPRA,
LO_PAGO,
LO_DELIVERY,
LO_RETIRADA,
LO_CLI_PERIODO,
LO_CLI_DATA_ENTREGA

FROM loja WHERE LO_EVENTO=%evento% AND LO_COD IN (
	SELECT LIA_COMPRA FROM [foliatropical2014].[dbo].[loja_itens_adicionais] WHERE LIA_ADICIONAL IN (
		SELECT VA_COD FROM [foliatropical2014].[dbo].[vendas_adicionais] WHERE (VA_NOME_EXIBICAO='transfer' OR VA_NOME_EXIBICAO='transferinout') AND VA_BLOCK=0 AND D_E_L_E_T_=0
	)
) AND LO_BLOCK=0 AND D_E_L_E_T_=0;


DECLARE @total TABLE (COD INT, QTDE INT DEFAULT 0);
INSERT INTO @total (COD, QTDE)
SELECT LI_COMPRA, COUNT(LI_COD) FROM loja_itens WHERE D_E_L_E_T_=0 GROUP BY LI_COMPRA;


DECLARE @agendados TABLE (COD INT, QTDE INT DEFAULT 0);
INSERT INTO @agendados (COD, QTDE)
SELECT l.LI_COMPRA, COUNT(t.TA_ITEM) FROM transportes_agendamento t, loja_itens l WHERE l.LI_COD=t.TA_ITEM AND t.D_E_L_E_T_=0 AND l.D_E_L_E_T_=0 GROUP BY l.LI_COMPRA;


DECLARE @loja_total TABLE (LO_COD INT, LO_CLIENTE INT, LO_FORMA_PAGAMENTO INT, LO_VALOR_TOTAL DECIMAL(10,2), LO_DATA_COMPRA DATETIME, LO_PAGO TINYINT, LO_DELIVERY TINYINT, LO_RETIRADA VARCHAR(255), LO_CLI_PERIODO VARCHAR(255), LO_CLI_DATA_ENTREGA DATETIME);

INSERT INTO @loja_total (LO_COD, LO_CLIENTE, LO_FORMA_PAGAMENTO, LO_VALOR_TOTAL, LO_DATA_COMPRA, LO_PAGO, LO_DELIVERY, LO_RETIRADA, LO_CLI_PERIODO, LO_CLI_DATA_ENTREGA)
SELECT LO_COD, 
LO_CLIENTE, 
LO_FORMA_PAGAMENTO, 
LO_VALOR_TOTAL, 
LO_DATA_COMPRA,
LO_PAGO,
LO_DELIVERY,
LO_RETIRADA,
LO_CLI_PERIODO,
LO_CLI_DATA_ENTREGA

FROM (
	SELECT
	l.*,
	ISNULL(t.QTDE, 0) AS TOTAL,
	ISNULL(p.QTDE, 0) AS AGENDADOS

	FROM @loja l 
	LEFT JOIN @total t ON l.LO_COD = t.COD
	LEFT JOIN @agendados p ON l.LO_COD = p.COD
) S WHERE (TOTAL - AGENDADOS) > 0;


SELECT 
MAX(l.LO_COD) AS VOUCHER,
MAX(c.NOMEPARC) AS CLIENTE,
MAX(c.TELEFONE) AS 'TELEFONE CLIENTE',
MAX(c.EMAIL) AS 'EMAIL CLIENTE',
MAX(CASE WHEN tp.TI_NOME='Lounge' THEN 'Folia Tropical' ELSE tp.TI_NOME END) AS TIPO,
MAX(li.LI_ID) AS ITEM,
MAX(s.ES_NOME) AS SETOR,
MAX(ISNULL(v.VE_FILA,'')) AS FILA,
--MAX(ISNULL(v.VE_VAGAS,'')) AS VAGAS,
MAX(CONVERT(VARCHAR, d.ED_DATA, 103)) AS DATA,

MAX(ISNULL(CASE WHEN (l.LO_DELIVERY=0 AND l.LO_RETIRADA IS NOT NULL) THEN UPPER(l.LO_RETIRADA) ELSE '' END, '')) AS RETIRADA,
MAX(ISNULL(CASE WHEN (l.LO_DELIVERY=0 AND l.LO_RETIRADA IS NOT NULL) THEN UPPER(l.LO_CLI_PERIODO) ELSE '' END, '')) AS 'PERÍODO RETIRADA',
MAX(ISNULL(CASE WHEN (l.LO_DELIVERY=0 AND l.LO_RETIRADA IS NOT NULL) THEN CONVERT(VARCHAR, l.LO_CLI_DATA_ENTREGA, 103) ELSE '' END, '')) AS 'DATA RETIRADA',

MAX(CASE 
	WHEN l.LO_PAGO=1 THEN 'PAGO' 
	WHEN l.LO_FORMA_PAGAMENTO='5' THEN 'RESERVA'
	ELSE '' END) AS PAGO

FROM @loja_total l 
LEFT JOIN [foliatropical2014].[dbo].[loja_itens] li ON li.LI_COMPRA=l.LO_COD
LEFT JOIN @vendas v ON v.VE_COD = li.LI_INGRESSO
LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE
LEFT JOIN @adicionais a ON a.COMPRA = l.LO_COD
LEFT JOIN [foliatropical2014].[dbo].[tipos] tp ON tp.TI_COD=v.VE_TIPO
LEFT JOIN [foliatropical2014].[dbo].[eventos_dias] d ON d.ED_COD=v.VE_DIA
LEFT JOIN [foliatropical2014].[dbo].[eventos_setores] s ON s.ES_COD=v.VE_SETOR

WHERE li.D_E_L_E_T_=0 AND d.D_E_L_E_T_=0 AND tp.D_E_L_E_T_=0 AND s.D_E_L_E_T_=0
GROUP BY li.LI_INGRESSO, li.LI_COMPRA
ORDER BY VOUCHER ASC, ITEM ASC;
