--Relatorio de Marketing
DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), EMAIL VARCHAR(255), SEXO VARCHAR(5), FAX VARCHAR(20), TELEFONE VARCHAR(20), DDD VARCHAR(20), DDD_CELULAR VARCHAR(20), DDI VARCHAR(20), DDI_CELULAR VARCHAR(20));

INSERT INTO @clientes (CODPARC, NOMEPARC, EMAIL, SEXO, FAX, TELEFONE, DDD, DDD_CELULAR, DDI, DDI_CELULAR)
SELECT CODPARC, NOMEPARC, EMAIL, SEXO, FAX, TELEFONE, DDD, DDD_CELULAR, DDI, DDI_CELULAR FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';

DECLARE @vendas TABLE (VE_COD INT, VE_TIPO INT, VE_ESTOQUE INT, VE_SETOR INT, VE_DIA INT, VE_FILA VARCHAR(255), VE_VAGAS INT, VE_TIPO_ESPECIFICO VARCHAR(255));

INSERT INTO @vendas (VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO)
SELECT VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO FROM [foliatropical2014].[dbo].[vendas] WHERE VE_BLOCK=0 AND D_E_L_E_T_=0;


DECLARE @loja TABLE (LO_COD INT, LO_CLIENTE INT, LO_PARCEIRO INT, LO_VENDEDOR INT, LO_DATA_COMPRA DATETIME, LO_VALOR_TOTAL FLOAT, LO_VALOR_PARCIAL FLOAT, LO_VALOR_ITEM FLOAT, LO_VALOR_ITEM_TABELA FLOAT, LO_VALOR_INGRESSOS FLOAT, LO_VALOR_ADICIONAIS FLOAT, LO_VALOR_TRANSFER FLOAT, LO_VALOR_DELIVERY FLOAT, LO_VALOR_DESCONTO FLOAT, LO_VALOR_OVER_INTERNO FLOAT, LO_VALOR_OVER_EXTERNO FLOAT, LO_COMISSAO INT, LO_COMISSAO_RETIDA TINYINT, LO_COMISSAO_PAGA TINYINT, LO_PAGO TINYINT, LO_DESCONTO_FOLIA TINYINT, LO_DESCONTO_FRISA TINYINT, LO_TID VARCHAR(255), LO_FORMA_PAGAMENTO INT, LI_INGRESSO INT, QTDE INT, ITENS INT);


INSERT INTO @loja (LO_COD, LO_CLIENTE, LO_PARCEIRO, LO_VENDEDOR, LO_DATA_COMPRA, LO_VALOR_TOTAL, LO_VALOR_PARCIAL, LO_VALOR_ITEM, LO_VALOR_ITEM_TABELA, LO_VALOR_INGRESSOS, LO_VALOR_ADICIONAIS, LO_VALOR_TRANSFER, LO_VALOR_DELIVERY, LO_VALOR_DESCONTO, LO_VALOR_OVER_INTERNO, LO_VALOR_OVER_EXTERNO, LO_COMISSAO, LO_COMISSAO_RETIDA, LO_COMISSAO_PAGA, LO_PAGO, LO_DESCONTO_FOLIA, LO_DESCONTO_FRISA, LO_TID, LO_FORMA_PAGAMENTO, LI_INGRESSO, QTDE, ITENS)
SELECT l.LO_COD, l.LO_CLIENTE, MAX(l.LO_PARCEIRO), MAX(l.LO_VENDEDOR),MAX(l.LO_DATA_COMPRA), MAX(l.LO_VALOR_TOTAL), MAX(l.LO_VALOR_PARCIAL), li.LI_VALOR, li.LI_VALOR_TABELA /*(li.LI_VALOR + li.LI_DESCONTO - li.LI_OVER_INTERNO - li.LI_OVER_EXTERNO)*/, MAX(l.LO_VALOR_INGRESSOS), li.LI_VALOR_ADICIONAIS, li.LI_VALOR_TRANSFER, MAX(l.LO_VALOR_DELIVERY), li.LI_DESCONTO, li.LI_OVER_INTERNO, li.LI_OVER_EXTERNO, MAX(l.LO_COMISSAO), MAX(l.LO_COMISSAO_RETIDA), MAX(l.LO_COMISSAO_PAGA), MAX(l.LO_PAGO), MAX(l.LO_DESCONTO_FOLIA), MAX(l.LO_DESCONTO_FRISA), MAX(l.LO_TID), MAX(l.LO_FORMA_PAGAMENTO), li.LI_INGRESSO, COUNT (li.LI_COD), MAX(l.LO_NUM_ITENS)
FROM [foliatropical2014].[dbo].[loja] l, [foliatropical2014].[dbo].[loja_itens] li WHERE l.LO_PAGO=1 AND l.LO_COD=li.LI_COMPRA AND l.D_E_L_E_T_=0 AND li.D_E_L_E_T_=0 /*vendedor*/
GROUP BY li.LI_INGRESSO, l.LO_COD, l.LO_CLIENTE, li.LI_VALOR, li.LI_VALOR_TABELA, li.LI_VALOR_TRANSFER, li.LI_VALOR_ADICIONAIS, li.LI_DESCONTO, li.LI_OVER_INTERNO, li.LI_OVER_EXTERNO;


SELECT 
MAX(ISNULL(ANO, '')) AS ANO,
MAX(ISNULL(DATA_COMPRA, '')) AS 'DATA DA COMPRA',
MAX(ISNULL(CLIENTE, '')) AS CLIENTE,
MAX(ISNULL(TIPO, '')) AS TIPO,
MAX(ISNULL(ESPECIFICO, '')) AS ESPECIFICO,
MAX(ISNULL(DIA, '')) AS DIA,
MAX(ISNULL(SETOR, '')) AS SETOR,
MAX(ISNULL(FILA, '')) AS FILA,
MAX(ISNULL(VAGAS, '')) AS VAGAS,
MAX(ISNULL(TELEFONE, '')) AS TELEFONE,
MAX(ISNULL(CELULAR, '')) AS CELULAR,
MAX(ISNULL(EMAIL, '')) AS EMAIL,
MAX(ISNULL(SEXO, '')) AS SEXO

FROM (
	SELECT

	c.NOMEPARC AS CLIENTE,
	c.EMAIL AS EMAIL,
	CASE WHEN c.TELEFONE <> '' AND c.TELEFONE IS NOT NULL THEN CONCAT('+', RTRIM(LTRIM(CAST(ptelefone.PAIS_PHONECODE AS CHAR))),' (', RTRIM(LTRIM(CAST(c.DDD AS CHAR))), ') ', RTRIM(LTRIM(CAST(c.TELEFONE AS CHAR)))) ELSE '' END AS TELEFONE,
	CASE WHEN c.FAX <> '' AND c.FAX IS NOT NULL THEN CONCAT('+', RTRIM(LTRIM(CAST(pcelular.PAIS_PHONECODE AS CHAR))),' (', RTRIM(LTRIM(CAST(c.DDD_CELULAR AS CHAR))), ') ', RTRIM(LTRIM(CAST(c.FAX AS CHAR)))) ELSE '' END AS CELULAR,
	CASE WHEN c.SEXO = 'M' THEN 'Masculino' WHEN c.SEXO = 'F' THEN 'Feminino' ELSE '' END AS SEXO,
	
	YEAR(l.LO_DATA_COMPRA) AS ANO,
	l.LO_DATA_COMPRA AS DATA_COMPRA,

	CASE WHEN t.TI_NOME='Lounge' THEN 'Folia Tropical' ELSE t.TI_NOME END AS TIPO,
	ISNULL(v.VE_TIPO_ESPECIFICO,'') AS ESPECIFICO,
	CONVERT(VARCHAR, d.ED_DATA, 103) AS DIA,
	s.ES_NOME AS SETOR,
	ISNULL(v.VE_FILA,'') AS FILA,
	ISNULL(v.VE_VAGAS,'') AS VAGAS

	FROM @loja l
	LEFT JOIN @vendas v ON v.VE_COD = l.LI_INGRESSO
	LEFT JOIN [foliatropical2014].[dbo].[tipos] t ON t.TI_COD=v.VE_TIPO
	LEFT JOIN [foliatropical2014].[dbo].[eventos_dias] d ON d.ED_COD=v.VE_DIA
	LEFT JOIN [foliatropical2014].[dbo].[eventos_setores] s ON s.ES_COD=v.VE_SETOR
	LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE
	LEFT JOIN [parceiros].[dbo].[pais] ptelefone ON ptelefone.PAIS_SIGLA = c.DDI
	LEFT JOIN [parceiros].[dbo].[pais] pcelular ON pcelular.PAIS_SIGLA = c.DDI_CELULAR
	
) S GROUP BY ANO, CLIENTE ORDER BY ANO ASC, CLIENTE ASC;

