--Relatorio de Agendamentos Pendentes

DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), EMAIL VARCHAR(255), TELEFONE VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC, EMAIL, TELEFONE)
SELECT CODPARC, NOMEPARC, EMAIL, TELEFONE FROM [SANKHYA_PROD].[sankhya].[TGFPAR] WHERE CLIENTE='S';

DECLARE @loja TABLE (LO_COD INT, LO_CLIENTE INT, LO_FORMA_PAGAMENTO INT, LO_VALOR_TOTAL DECIMAL(10,2), LO_DATA_COMPRA DATETIME, LO_PAGO TINYINT);

INSERT INTO @loja (LO_COD, LO_CLIENTE, LO_FORMA_PAGAMENTO, LO_VALOR_TOTAL, LO_DATA_COMPRA, LO_PAGO)
SELECT LO_COD, 
LO_CLIENTE, 
LO_FORMA_PAGAMENTO, 
LO_VALOR_TOTAL, 
LO_DATA_COMPRA,
LO_PAGO
FROM loja WHERE LO_EVENTO=1 AND LO_COD IN (
	SELECT LIA_COMPRA FROM [foliatropical].[dbo].[loja_itens_adicionais] WHERE LIA_ADICIONAL IN (
		SELECT VA_COD FROM [foliatropical].[dbo].[vendas_adicionais] WHERE (VA_NOME_EXIBICAO='transfer' OR VA_NOME_EXIBICAO='transferinout') AND VA_BLOCK=0 AND D_E_L_E_T_=0
	)
) AND LO_BLOCK=0 AND D_E_L_E_T_=0;

DECLARE @total TABLE (COD INT, QTDE INT DEFAULT 0);
INSERT INTO @total (COD, QTDE)
SELECT LI_COMPRA, COUNT(LI_COD) FROM loja_itens WHERE D_E_L_E_T_=0 GROUP BY LI_COMPRA;

DECLARE @agendados TABLE (COD INT, QTDE INT DEFAULT 0);
INSERT INTO @agendados (COD, QTDE)
SELECT l.LI_COMPRA, COUNT(t.TA_ITEM) FROM transportes_agendamento t, loja_itens l WHERE l.LI_COD=t.TA_ITEM AND t.D_E_L_E_T_=0 AND l.D_E_L_E_T_=0 GROUP BY l.LI_COMPRA;

SELECT * FROM (
	SELECT
	l.LO_COD AS VOUCHER,
	c.NOMEPARC AS CLIENTE,
	c.EMAIL AS EMAIL,
	c.TELEFONE AS TELEFONE,
	ISNULL(t.QTDE, 0) AS TOTAL,
	ISNULL(p.QTDE, 0) AS AGENDADOS,
	(CONVERT(VARCHAR, l.LO_DATA_COMPRA, 103)+' '+SUBSTRING(CONVERT(VARCHAR, l.LO_DATA_COMPRA, 108),1,5)) AS DATA,
	l.LO_VALOR_TOTAL AS VALOR_TOTAL,
	f.FP_NOME AS FORMA_PAGAMENTO,
	CASE WHEN l.LO_PAGO=1 THEN 'PAGO' ELSE '' END AS PAGO
	
	FROM @loja l 
	LEFT JOIN @total t ON l.LO_COD = t.COD
	LEFT JOIN @agendados p ON l.LO_COD = p.COD
	LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE
	LEFT JOIN [foliatropical].[dbo].[formas_pagamento] f ON f.FP_COD=l.LO_FORMA_PAGAMENTO) S 
WHERE (TOTAL - AGENDADOS) > 0
ORDER BY VOUCHER ASC;