--Relatorio de Comentários

DECLARE @vendas TABLE (VE_COD INT, VE_TIPO INT, VE_ESTOQUE INT, VE_SETOR INT, VE_DIA INT, VE_FILA VARCHAR(255), VE_VAGAS INT, VE_TIPO_ESPECIFICO VARCHAR(255));

INSERT INTO @vendas (VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO)
SELECT VE_COD, VE_TIPO, VE_ESTOQUE, VE_SETOR, VE_DIA, VE_FILA, VE_VAGAS, VE_TIPO_ESPECIFICO FROM [foliatropical2014].[dbo].[vendas] WHERE VE_BLOCK=0 AND D_E_L_E_T_=0;

DECLARE @loja TABLE (LI_COD INT, LO_COD INT, LO_CLIENTE INT, LO_VENDEDOR INT, LO_DATA_COMPRA DATETIME, LO_VALOR_TOTAL FLOAT, LO_VALOR_PARCIAL FLOAT, LO_VALOR_ITEM FLOAT, LO_VALOR_ITEM_TABELA FLOAT, LO_VALOR_INGRESSOS FLOAT, LO_VALOR_ADICIONAIS FLOAT, LO_VALOR_TRANSFER FLOAT, LO_VALOR_DELIVERY FLOAT, LO_VALOR_DESCONTO FLOAT, LO_VALOR_OVER_INTERNO FLOAT, LO_VALOR_OVER_EXTERNO FLOAT, LO_COMISSAO INT, LO_PAGO TINYINT, LO_TID VARCHAR(255), LO_FORMA_PAGAMENTO INT, LI_INGRESSO INT, QTDE INT, ITENS INT);


INSERT INTO @loja (LI_COD, LO_COD, LO_CLIENTE, LO_VENDEDOR, LO_DATA_COMPRA, LO_VALOR_TOTAL, LO_VALOR_PARCIAL, LO_VALOR_ITEM, LO_VALOR_ITEM_TABELA, LO_VALOR_INGRESSOS, LO_VALOR_ADICIONAIS, LO_VALOR_TRANSFER, LO_VALOR_DELIVERY, LO_VALOR_DESCONTO, LO_VALOR_OVER_INTERNO, LO_VALOR_OVER_EXTERNO, LO_COMISSAO, LO_PAGO, LO_TID, LO_FORMA_PAGAMENTO, LI_INGRESSO, QTDE, ITENS)
SELECT MAX(li.LI_COD), l.LO_COD, l.LO_CLIENTE, MAX(l.LO_VENDEDOR), MAX(l.LO_DATA_COMPRA), MAX(l.LO_VALOR_TOTAL), MAX(l.LO_VALOR_PARCIAL), li.LI_VALOR, li.LI_VALOR_TABELA, MAX(l.LO_VALOR_INGRESSOS), li.LI_VALOR_ADICIONAIS, li.LI_VALOR_TRANSFER, MAX(l.LO_VALOR_DELIVERY), li.LI_DESCONTO, li.LI_OVER_INTERNO, li.LI_OVER_EXTERNO, MAX(l.LO_COMISSAO), MAX(l.LO_PAGO), MAX(l.LO_TID), MAX(l.LO_FORMA_PAGAMENTO), li.LI_INGRESSO, COUNT (li.LI_COD), MAX(l.LO_NUM_ITENS)
FROM [foliatropical2014].[dbo].[loja] l, [foliatropical2014].[dbo].[loja_itens] li WHERE l.LO_EVENTO=%evento% AND l.LO_COD=li.LI_COMPRA AND l.D_E_L_E_T_=0 AND li.D_E_L_E_T_=0
GROUP BY li.LI_INGRESSO, l.LO_COD, l.LO_CLIENTE, li.LI_VALOR, li.LI_VALOR_TABELA, li.LI_VALOR_TRANSFER, li.LI_VALOR_ADICIONAIS, li.LI_DESCONTO, li.LI_OVER_INTERNO, li.LI_OVER_EXTERNO;


DECLARE @clientes TABLE (CODPARC INT, NOMEPARC VARCHAR(255), EMAIL VARCHAR(255), CGC_CPF VARCHAR(255));

INSERT INTO @clientes (CODPARC, NOMEPARC, EMAIL, CGC_CPF)
SELECT CODPARC, NOMEPARC, EMAIL, CGC_CPF FROM [parceiros].[dbo].[TGFPAR] WHERE CLIENTE='S';

SELECT

VOUCHER,
VENDEDOR_INTERNO AS 'VENDEDOR INTERNO',
CLIENTE,
QTDE,
VALOR_ITEM AS 'VALOR ITEM',
(VALOR_TOTAL_VENDA - OVER_EXTERNO_TOTAL - VALOR_COMISSAO) AS LUCRO,
TIPO,
ESPECIFICO,
DATA,
SETOR,
FILA,
VAGAS,
PAGO,
FORMA_PAGAMENTO AS 'FORMA PAGAMENTO',
DATA_COMPRA AS 'DATA COMPRA',
COMENTARIO AS 'COMENTÁRIO',
COMENTARIO_INTERNO AS 'COMENTÁRIO INTERNO'

FROM (

	SELECT
	*,
	(TRANSFER_UNITARIO * QTDE) AS TRANSFER,
	(DELIVERY_TOTAL / ITENS) AS DELIVERY,
	(PRECO_AUTORIZADO * QTDE) AS VALOR_TOTAL_CALCULO_COMISSAO,
	(PRECO_PRATICADO * QTDE) AS PRECO_TOTAL_PRATICADO,
	(PRECO_PRATICADO + ADICIONAIS) AS VALOR_TOTAL_VENDA,
	(OVER_EXTERNO * QTDE) AS OVER_EXTERNO_TOTAL,
	((VALOR_ITEM - OVER_EXTERNO + OVER_INTERNO) * COMISSAO / 100) AS VALOR_COMISSAO
	FROM (
		SELECT 
		l.LO_COD AS VOUCHER,
		u.US_NOME AS VENDEDOR_INTERNO,
		c.NOMEPARC AS CLIENTE,
		l.LO_VALOR_ITEM_TABELA AS VALOR_TABELA,
		l.LO_VALOR_DESCONTO AS VALOR_DESCONTO,
		l.LO_VALOR_OVER_INTERNO AS OVER_INTERNO,
		(l.LO_VALOR_ITEM_TABELA - l.LO_VALOR_DESCONTO + l.LO_VALOR_OVER_INTERNO) AS PRECO_AUTORIZADO,
		l.LO_VALOR_OVER_EXTERNO AS OVER_EXTERNO,
		(l.LO_VALOR_ITEM_TABELA + l.LO_VALOR_OVER_EXTERNO) AS PRECO_PRATICADO,
		l.QTDE AS QTDE,
		l.ITENS AS ITENS,
		l.LO_VALOR_ADICIONAIS AS ADICIONAIS,
		l.LO_VALOR_TRANSFER AS TRANSFER_UNITARIO,
		l.LO_VALOR_DELIVERY AS DELIVERY_TOTAL,
		l.LO_COMISSAO AS COMISSAO,
		l.LO_VALOR_ITEM AS VALOR_ITEM,
		
		CASE WHEN t.TI_NOME='Lounge' THEN 'Folia Tropical' ELSE t.TI_NOME END AS TIPO,
		ISNULL(v.VE_TIPO_ESPECIFICO,'') AS ESPECIFICO,
		--REPLACE(d.ED_NOME,'°','o') AS DIA,
		CONVERT(VARCHAR, d.ED_DATA, 103) AS DATA,
		s.ES_NOME AS SETOR,
		ISNULL(v.VE_FILA,'') AS FILA,
		ISNULL(v.VE_VAGAS,'') AS VAGAS,
		CASE WHEN l.LO_PAGO=1 THEN 'PAGO' ELSE '' END AS PAGO,
		f.FP_NOME AS FORMA_PAGAMENTO,
		ISNULL(CAST(REPLACE(REPLACE(CAST(lc.LC_COMENTARIO AS NVarchar(MAX)), CHAR(10),' '), CHAR(13),' ') AS NText), '-') AS COMENTARIO,
		ISNULL(CAST(REPLACE(REPLACE(CAST(lci.LC_COMENTARIO AS NVarchar(MAX)), CHAR(10),' '), CHAR(13),' ') AS NText), '-') AS COMENTARIO_INTERNO,
		l.LO_TID AS TID,
		l.LO_DATA_COMPRA AS DATA_COMPRA,
		d.ED_DATA

		FROM @loja l
		LEFT JOIN @vendas v ON v.VE_COD = l.LI_INGRESSO
		LEFT JOIN @clientes c ON c.CODPARC = l.LO_CLIENTE
		LEFT JOIN [foliatropical2014].[dbo].[tipos] t ON t.TI_COD=v.VE_TIPO
		LEFT JOIN [foliatropical2014].[dbo].[eventos_dias] d ON d.ED_COD=v.VE_DIA
		LEFT JOIN [foliatropical2014].[dbo].[eventos_setores] s ON s.ES_COD=v.VE_SETOR
		LEFT JOIN [foliatropical2014].[dbo].[formas_pagamento] f ON f.FP_COD=l.LO_FORMA_PAGAMENTO
		LEFT JOIN [foliatropical2014].[dbo].[loja_comentarios] lc ON lc.LC_COMPRA=l.LO_COD AND lc.LC_ITEM=l.LI_COD
		LEFT JOIN [foliatropical2014].[dbo].[loja_comentarios_internos] lci ON lci.LC_COMPRA=l.LO_COD AND lci.LC_ITEM=l.LI_COD
		LEFT JOIN [foliatropical2014].[dbo].[usuarios] u ON l.LO_VENDEDOR=u.US_COD
		WHERE d.D_E_L_E_T_=0 AND t.D_E_L_E_T_=0 AND s.D_E_L_E_T_=0
	) S 
) S ORDER BY TIPO ASC, ED_DATA ASC