SELECT
LO_COD, 
LO_CLIENTE, 
LO_PARCEIRO, 
LO_FORMA_PAGAMENTO, 
LO_STATUS_TRANSACAO, 
LO_VALOR_INGRESSOS,
LO_VALOR_DESCONTO,
LO_VALOR_OVER_INTERNO,
LO_VALOR_OVER_EXTERNO,
LO_ENVIADO,
LO_DATA_COMPRA,
LO_COMISSAO,
LO_COMISSAO_RETIDA,
LO_COMISSAO_PAGA,
LO_ORIGEM,
(CONVERT(VARCHAR, LO_DATA_COMPRA, 103)+' '+SUBSTRING(CONVERT(VARCHAR, LO_DATA_COMPRA, 108),1,5)) AS DATA, 
(CONVERT(VARCHAR, LO_DATA_PAGAMENTO, 103)+' '+SUBSTRING(CONVERT(VARCHAR, LO_DATA_PAGAMENTO, 108),1,5)) AS DATA_PAGAMENTO,
(SUBSTRING(CONVERT(VARCHAR, LO_DATA_COMPRA, 103),1,5)+' '+SUBSTRING(CONVERT(VARCHAR, LO_DATA_COMPRA, 108),1,5)) AS DATA_MINI, 
(SUBSTRING(CONVERT(VARCHAR, LO_DATA_PAGAMENTO, 103),1,5)+' '+SUBSTRING(CONVERT(VARCHAR, LO_DATA_PAGAMENTO, 108),1,5)) AS DATA_PAGAMENTO_MINI, 
ISNULL(DATEDIFF (DAY, LO_DATA_PAGAMENTO, GETDATE()), 6) AS DIFERENCA
FROM [foliatropical2014].[dbo].[usuarios_loja] loja (NOLOCK) WHERE 
LO_PAGO='1' AND LO_COMISSAO>0 AND LO_BLOCK='0' AND D_E_L_E_T_='0' AND LO_DATA_COMPRA > '2017-04-02';